// GET CHORES FROM DB
export const REQUEST_CHORES_PENDING = 'REQUEST_CHORES_PENDING';
export const REQUEST_CHORES_SUCCESS = 'REQUEST_CHORES_SUCCESS';
export const REQUEST_CHORES_FAILED = 'REQUEST_CHORES_FAILED';

// PATCH CHORE (completed)
export const SUBMIT_CHORE_PENDING = 'SUBMIT_CHORE_PENDING';
export const SUBMIT_CHORE_SUCCESS = 'SUBMIT_CHORE_SUCCESS';
export const SUBMIT_CHORE_FAILED = 'SUBMIT_CHORE_FAILED';
