// GET CHORES FROM DB
export const REQUEST_CHORES_PENDING = 'REQUEST_CHORES_PENDING';
export const REQUEST_CHORES_SUCCESS = 'REQUEST_CHORES_SUCCESS';
export const REQUEST_CHORES_FAILED = 'REQUEST_CHORES_FAILED';

