// GET GROUPS FROM DB
export const REQUEST_GROUPS_PENDING = 'REQUEST_GROUPS_PENDING';
export const REQUEST_GROUPS_SUCCESS = 'REQUEST_GROUPS_SUCCESS';
export const REQUEST_GROUPS_FAILED = 'REQUEST_GROUPS_FAILED';

// CREATE CHORE GROUP 
export const CREATE_GROUP_PENDING = 'CREATE_GROUP_PENDING';
export const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS';
export const CREATE_GROUP_FAILED = 'CREATE_GROUP_FAILED';
