// CHANGE PASSWORD
export const PASSWORD_CHANGE_PENDING = 'PASSWORD_CHANGE_PENDING';
export const PASSWORD_CHANGE_SUCCESS = 'PASSWORD_CHANGE_SUCCESS';
export const PASSWORD_CHANGE_FAILED = 'PASSWORD_CHANGE_FAILED';

// DELETE ACCOUNT
export const DELETE_ACCOUNT_PENDING = 'DELETE_ACCOUNT_PENDING';
export const DELETE_ACCOUNT_SUCCESS ='DELETE_ACCOUNT_SUCCESS';
export const DELETE_ACCOUNT_FAILED = 'DELETE_ACCOUNT_FAILED';

// RESET PASSWORD
export const RESET_PASSWORD_PENDING = 'RESET_PASSWORD_PENDING';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED';

// CHECK RESET PASSWORD AUTH
export const RESET_AUTH_PENDING = 'RESET_AUTH_PENDING';
export const RESET_AUTH_SUCCESS = 'RESET_AUTH_SUCCESS';
export const RESET_AUTH_FAILED = 'RESET_AUTH_FAILED';