
// SIGNIN
export const REQUEST_SIGNIN_PENDING = 'REQUEST_SIGNIN_PENDING';
export const REQUEST_SIGNIN_SUCCESS = 'REQUEST_SIGNIN_SUCCESS';
export const REQUEST_SIGNIN_FAILED = 'REQUEST_SIGNIN_FAILED';

// REGISTER
export const REQUEST_REGISTER_PENDING = 'REQUEST_REGISTER_PENDING';
export const REQUEST_REGISTER_SUCCESS = 'REQUEST_REGISTER_SUCCESS';
export const REQUEST_REGISTER_FAILED = 'REQUEST_REGISTER_FAILED';

// SIGN OUT
export const SIGN_OUT_USER = 'SIGN_OUT_USER';

